# Create GitHub Action Secrets for your version of the application:
#   DEBRICKED_TOKEN should be the API token obtained from Debricked.
# Note: this action is on "workflow_dispatch" as the Debricked GitHub App is being used for scanning.
name: Fortify SCA Scan

on:
  workflow_dispatch:

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions@v4
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
